/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cartpole_model_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {0, 3, 5};
static const casadi_int casadi_s1[4] = {1, 2, 4, 6};
static const casadi_int casadi_s2[14] = {4, 4, 0, 0, 3, 3, 7, 0, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s3[14] = {4, 4, 0, 2, 3, 5, 7, 1, 3, 3, 1, 3, 1, 3};
static const casadi_int casadi_s4[11] = {4, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3};
static const casadi_int casadi_s5[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s6[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s7[3] = {0, 0, 0};
static const casadi_int casadi_s8[7] = {4, 1, 0, 3, 0, 2, 3};
static const casadi_int casadi_s9[3] = {4, 0, 0};

/* cartpole_model_impl_dae_jac_x_xdot_u_z:(i0[4],i1[4],i2,i3[],i4[],i5[])->(o0[4x4,7nz],o1[4x4,4nz],o2[4x1,3nz],o3[4x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real *w0=w+0, w1, w2, w3, w4, w5, *w6=w+12, w7, w8, w9, w10, w11, w12, w13, w14, w15, *w17=w+24, *w18=w+27, *w19=w+31, *w20=w+38, *w21=w+42;
  /* #0: @0 = zeros(4x4,7nz) */
  casadi_clear(w0, 7);
  /* #1: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = sq(@1) */
  w2 = casadi_sq( w1 );
  /* #3: @3 = -0.05 */
  w3 = -5.0000000000000003e-02;
  /* #4: @4 = input[0][1] */
  w4 = arg[0] ? arg[0][1] : 0;
  /* #5: @5 = cos(@4) */
  w5 = cos( w4 );
  /* #6: @6 = ones(4x1,3nz) */
  casadi_fill(w6, 3, 1.);
  /* #7: {NULL, @7, NULL, NULL} = vertsplit(@6) */
  w7 = w6[1];
  /* #8: @8 = (@5*@7) */
  w8  = (w5*w7);
  /* #9: @9 = (@3*@8) */
  w9  = (w3*w8);
  /* #10: @9 = (@2*@9) */
  w9  = (w2*w9);
  /* #11: @10 = 0.981 */
  w10 = 9.8100000000000009e-01;
  /* #12: @11 = (@10*@5) */
  w11  = (w10*w5);
  /* #13: @12 = (@11*@8) */
  w12  = (w11*w8);
  /* #14: @4 = sin(@4) */
  w4 = sin( w4 );
  /* #15: @7 = (@4*@7) */
  w7  = (w4*w7);
  /* #16: @10 = (@10*@7) */
  w10 *= w7;
  /* #17: @10 = (@4*@10) */
  w10  = (w4*w10);
  /* #18: @12 = (@12-@10) */
  w12 -= w10;
  /* #19: @9 = (@9+@12) */
  w9 += w12;
  /* #20: @12 = 1 */
  w12 = 1.;
  /* #21: @10 = 0.1 */
  w10 = 1.0000000000000001e-01;
  /* #22: @13 = sq(@5) */
  w13 = casadi_sq( w5 );
  /* #23: @13 = (@12-@13) */
  w13  = (w12-w13);
  /* #24: @13 = (@10*@13) */
  w13  = (w10*w13);
  /* #25: @12 = (@12+@13) */
  w12 += w13;
  /* #26: @9 = (@9/@12) */
  w9 /= w12;
  /* #27: @13 = (@3*@4) */
  w13  = (w3*w4);
  /* #28: @14 = (@13*@2) */
  w14  = (w13*w2);
  /* #29: @11 = (@11*@4) */
  w11 *= w4;
  /* #30: @14 = (@14+@11) */
  w14 += w11;
  /* #31: @11 = input[2][0] */
  w11 = arg[2] ? arg[2][0] : 0;
  /* #32: @14 = (@14+@11) */
  w14 += w11;
  /* #33: @14 = (@14/@12) */
  w14 /= w12;
  /* #34: @14 = (@14/@12) */
  w14 /= w12;
  /* #35: @15 = (2.*@5) */
  w15 = (2.* w5 );
  /* #36: @15 = (@15*@7) */
  w15 *= w7;
  /* #37: @10 = (@10*@15) */
  w10 *= w15;
  /* #38: @14 = (@14*@10) */
  w14 *= w10;
  /* #39: @9 = (@9-@14) */
  w9 -= w14;
  /* #40: @16 = 00 */
  /* #41: @14 = (@3*@5) */
  w14  = (w3*w5);
  /* #42: @15 = (@14*@8) */
  w15  = (w14*w8);
  /* #43: @3 = (@3*@7) */
  w3 *= w7;
  /* #44: @3 = (@4*@3) */
  w3  = (w4*w3);
  /* #45: @15 = (@15-@3) */
  w15 -= w3;
  /* #46: @15 = (@2*@15) */
  w15  = (w2*w15);
  /* #47: @3 = 10.791 */
  w3 = 1.0791000000000002e+01;
  /* #48: @8 = (@3*@8) */
  w8  = (w3*w8);
  /* #49: @15 = (@15+@8) */
  w15 += w8;
  /* #50: @7 = (@11*@7) */
  w7  = (w11*w7);
  /* #51: @15 = (@15-@7) */
  w15 -= w7;
  /* #52: @15 = (@15/@12) */
  w15 /= w12;
  /* #53: @14 = (@14*@4) */
  w14 *= w4;
  /* #54: @2 = (@14*@2) */
  w2  = (w14*w2);
  /* #55: @3 = (@3*@4) */
  w3 *= w4;
  /* #56: @2 = (@2+@3) */
  w2 += w3;
  /* #57: @11 = (@11*@5) */
  w11 *= w5;
  /* #58: @2 = (@2+@11) */
  w2 += w11;
  /* #59: @2 = (@2/@12) */
  w2 /= w12;
  /* #60: @2 = (@2/@12) */
  w2 /= w12;
  /* #61: @2 = (@2*@10) */
  w2 *= w10;
  /* #62: @15 = (@15-@2) */
  w15 -= w2;
  /* #63: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #64: @6 = vertcat(@9, @16, @9, @15) */
  rr=w6;
  *rr++ = w9;
  *rr++ = w9;
  *rr++ = w15;
  /* #65: @6 = (-@6) */
  for (i=0, rr=w6, cs=w6; i<3; ++i) *rr++ = (- *cs++ );
  /* #66: @17 = @6[:3] */
  for (rr=w17, ss=w6+0; ss!=w6+3; ss+=1) *rr++ = *ss;
  /* #67: (@0[0, 3, 5] = @17) */
  for (cii=casadi_s0, rr=w0, ss=w17; cii!=casadi_s0+3; ++cii, ++ss) rr[*cii] = *ss;
  /* #68: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #69: @9 = ones(4x1,1nz) */
  w9 = 1.;
  /* #70: {NULL, NULL, NULL, @15} = vertsplit(@9) */
  w15 = w9;
  /* #71: @1 = (@1*@15) */
  w1 *= w15;
  /* #72: @13 = (@13*@1) */
  w13 *= w1;
  /* #73: @13 = (@13/@12) */
  w13 /= w12;
  /* #74: @14 = (@14*@1) */
  w14 *= w1;
  /* #75: @14 = (@14/@12) */
  w14 /= w12;
  /* #76: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #77: @18 = vertcat(@13, @15, @13, @14) */
  rr=w18;
  *rr++ = w13;
  *rr++ = w15;
  *rr++ = w13;
  *rr++ = w14;
  /* #78: @18 = (-@18) */
  for (i=0, rr=w18, cs=w18; i<4; ++i) *rr++ = (- *cs++ );
  /* #79: (@0[1, 2, 4, 6] = @18) */
  for (cii=casadi_s1, rr=w0, ss=w18; cii!=casadi_s1+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #80: @19 = @0' */
  casadi_trans(w0,casadi_s3, w19, casadi_s2, iw);
  /* #81: output[0][0] = @19 */
  casadi_copy(w19, 7, res[0]);
  /* #82: @18 = zeros(4x4,4nz) */
  casadi_clear(w18, 4);
  /* #83: @20 = ones(4x1) */
  casadi_fill(w20, 4, 1.);
  /* #84: (@18[:4] = @20) */
  for (rr=w18+0, ss=w20; rr!=w18+4; rr+=1) *rr = *ss++;
  /* #85: @20 = @18' */
  casadi_trans(w18,casadi_s4, w20, casadi_s4, iw);
  /* #86: output[1][0] = @20 */
  casadi_copy(w20, 4, res[1]);
  /* #87: @17 = zeros(1x4,3nz) */
  casadi_clear(w17, 3);
  /* #88: @13 = (1./@12) */
  w13 = (1./ w12 );
  /* #89: @5 = (@5/@12) */
  w5 /= w12;
  /* #90: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #91: @6 = vertcat(@13, @16, @13, @5) */
  rr=w6;
  *rr++ = w13;
  *rr++ = w13;
  *rr++ = w5;
  /* #92: @6 = (-@6) */
  for (i=0, rr=w6, cs=w6; i<3; ++i) *rr++ = (- *cs++ );
  /* #93: @21 = @6[:3] */
  for (rr=w21, ss=w6+0; ss!=w6+3; ss+=1) *rr++ = *ss;
  /* #94: (@17[:3] = @21) */
  for (rr=w17+0, ss=w21; rr!=w17+3; rr+=1) *rr = *ss++;
  /* #95: output[2][0] = @17 */
  casadi_copy(w17, 3, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_model_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_model_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cartpole_model_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void cartpole_model_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cartpole_model_impl_dae_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int cartpole_model_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real cartpole_model_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_model_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_model_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_model_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s7;
    case 5: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_model_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s4;
    case 2: return casadi_s8;
    case 3: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 5;
  if (sz_w) *sz_w = 45;
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_jac_x_xdot_u_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 5*sizeof(casadi_int);
  if (sz_w) *sz_w = 45*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
