/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cartpole_model_impl_dae_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[3] = {0, 0, 0};

/* cartpole_model_impl_dae_fun:(i0[4],i1[4],i2,i3[0],i4[],i5[0])->(o0[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, *w4=w+4, w5, w6, w7, w8, w9, w10, w11, *w12=w+15;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #2: @2 = input[1][2] */
  w2 = arg[1] ? arg[1][2] : 0;
  /* #3: @3 = input[1][3] */
  w3 = arg[1] ? arg[1][3] : 0;
  /* #4: @4 = vertcat(@0, @1, @2, @3) */
  rr=w4;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  /* #5: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #6: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #7: @2 = -0.05 */
  w2 = -5.0000000000000003e-02;
  /* #8: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #9: @5 = sin(@3) */
  w5 = sin( w3 );
  /* #10: @6 = (@2*@5) */
  w6  = (w2*w5);
  /* #11: @7 = sq(@1) */
  w7 = casadi_sq( w1 );
  /* #12: @6 = (@6*@7) */
  w6 *= w7;
  /* #13: @8 = 0.981 */
  w8 = 9.8100000000000009e-01;
  /* #14: @3 = cos(@3) */
  w3 = cos( w3 );
  /* #15: @8 = (@8*@3) */
  w8 *= w3;
  /* #16: @8 = (@8*@5) */
  w8 *= w5;
  /* #17: @6 = (@6+@8) */
  w6 += w8;
  /* #18: @8 = input[2][0] */
  w8 = arg[2] ? arg[2][0] : 0;
  /* #19: @6 = (@6+@8) */
  w6 += w8;
  /* #20: @9 = 1 */
  w9 = 1.;
  /* #21: @10 = 0.1 */
  w10 = 1.0000000000000001e-01;
  /* #22: @11 = sq(@3) */
  w11 = casadi_sq( w3 );
  /* #23: @11 = (@9-@11) */
  w11  = (w9-w11);
  /* #24: @10 = (@10*@11) */
  w10 *= w11;
  /* #25: @9 = (@9+@10) */
  w9 += w10;
  /* #26: @6 = (@6/@9) */
  w6 /= w9;
  /* #27: @2 = (@2*@3) */
  w2 *= w3;
  /* #28: @2 = (@2*@5) */
  w2 *= w5;
  /* #29: @2 = (@2*@7) */
  w2 *= w7;
  /* #30: @7 = 10.791 */
  w7 = 1.0791000000000002e+01;
  /* #31: @7 = (@7*@5) */
  w7 *= w5;
  /* #32: @2 = (@2+@7) */
  w2 += w7;
  /* #33: @8 = (@8*@3) */
  w8 *= w3;
  /* #34: @2 = (@2+@8) */
  w2 += w8;
  /* #35: @2 = (@2/@9) */
  w2 /= w9;
  /* #36: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #37: @12 = vertcat(@0, @1, @6, @2) */
  rr=w12;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w6;
  *rr++ = w2;
  /* #38: @4 = (@4-@12) */
  for (i=0, rr=w4, cs=w12; i<4; ++i) (*rr++) -= (*cs++);
  /* #39: output[0][0] = @4 */
  casadi_copy(w4, 4, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_model_impl_dae_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_model_impl_dae_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cartpole_model_impl_dae_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void cartpole_model_impl_dae_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cartpole_model_impl_dae_fun_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int cartpole_model_impl_dae_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cartpole_model_impl_dae_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_model_impl_dae_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_model_impl_dae_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_model_impl_dae_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_model_impl_dae_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 19;
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 19*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
