/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cartpole_model_impl_dae_fun_jac_x_xdot_u_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[13] = {4, 4, 0, 0, 2, 3, 6, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s1[13] = {4, 4, 0, 1, 2, 4, 6, 2, 3, 1, 3, 1, 3};
static const casadi_int casadi_s2[11] = {4, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3};
static const casadi_int casadi_s3[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s4[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s5[3] = {0, 0, 0};
static const casadi_int casadi_s6[6] = {4, 1, 0, 2, 2, 3};

/* cartpole_model_impl_dae_fun_jac_x_xdot_u:(i0[4],i1[4],i2,i3[],i4[],i5[])->(o0[4],o1[4x4,6nz],o2[4x4,4nz],o3[4x1,2nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, *w4=w+4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+22, *w20=w+26, *w21=w+32, w23, w24, *w25=w+37, *w26=w+40, *w27=w+46, *w28=w+48, *w29=w+50;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #2: @2 = input[1][2] */
  w2 = arg[1] ? arg[1][2] : 0;
  /* #3: @3 = input[1][3] */
  w3 = arg[1] ? arg[1][3] : 0;
  /* #4: @4 = vertcat(@0, @1, @2, @3) */
  rr=w4;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  /* #5: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #6: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #7: @2 = -0.05 */
  w2 = -5.0000000000000003e-02;
  /* #8: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #9: @5 = sin(@3) */
  w5 = sin( w3 );
  /* #10: @6 = (@2*@5) */
  w6  = (w2*w5);
  /* #11: @7 = sq(@1) */
  w7 = casadi_sq( w1 );
  /* #12: @8 = (@6*@7) */
  w8  = (w6*w7);
  /* #13: @9 = 0.981 */
  w9 = 9.8100000000000009e-01;
  /* #14: @3 = cos(@3) */
  w3 = cos( w3 );
  /* #15: @10 = (@9*@3) */
  w10  = (w9*w3);
  /* #16: @11 = (@10*@5) */
  w11  = (w10*w5);
  /* #17: @8 = (@8+@11) */
  w8 += w11;
  /* #18: @11 = input[2][0] */
  w11 = arg[2] ? arg[2][0] : 0;
  /* #19: @8 = (@8+@11) */
  w8 += w11;
  /* #20: @12 = 1 */
  w12 = 1.;
  /* #21: @13 = 0.1 */
  w13 = 1.0000000000000001e-01;
  /* #22: @14 = sq(@3) */
  w14 = casadi_sq( w3 );
  /* #23: @14 = (@12-@14) */
  w14  = (w12-w14);
  /* #24: @14 = (@13*@14) */
  w14  = (w13*w14);
  /* #25: @12 = (@12+@14) */
  w12 += w14;
  /* #26: @8 = (@8/@12) */
  w8 /= w12;
  /* #27: @14 = (@2*@3) */
  w14  = (w2*w3);
  /* #28: @15 = (@14*@5) */
  w15  = (w14*w5);
  /* #29: @16 = (@15*@7) */
  w16  = (w15*w7);
  /* #30: @17 = 10.791 */
  w17 = 1.0791000000000002e+01;
  /* #31: @18 = (@17*@5) */
  w18  = (w17*w5);
  /* #32: @16 = (@16+@18) */
  w16 += w18;
  /* #33: @18 = (@11*@3) */
  w18  = (w11*w3);
  /* #34: @16 = (@16+@18) */
  w16 += w18;
  /* #35: @16 = (@16/@12) */
  w16 /= w12;
  /* #36: @18 = (2.*@16) */
  w18 = (2.* w16 );
  /* #37: @19 = vertcat(@0, @1, @8, @18) */
  rr=w19;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w8;
  *rr++ = w18;
  /* #38: @4 = (@4-@19) */
  for (i=0, rr=w4, cs=w19; i<4; ++i) (*rr++) -= (*cs++);
  /* #39: output[0][0] = @4 */
  casadi_copy(w4, 4, res[0]);
  /* #40: @20 = zeros(4x4,6nz) */
  casadi_clear(w20, 6);
  /* #41: @21 = ones(4x1,3nz) */
  casadi_fill(w21, 3, 1.);
  /* #42: {NULL, @0, @18, NULL} = vertsplit(@21) */
  w0 = w21[1];
  w18 = w21[2];
  /* #43: @22 = 00 */
  /* #44: @23 = (@3*@0) */
  w23  = (w3*w0);
  /* #45: @24 = (@2*@23) */
  w24  = (w2*w23);
  /* #46: @24 = (@7*@24) */
  w24  = (w7*w24);
  /* #47: @10 = (@10*@23) */
  w10 *= w23;
  /* #48: @0 = (@5*@0) */
  w0  = (w5*w0);
  /* #49: @9 = (@9*@0) */
  w9 *= w0;
  /* #50: @9 = (@5*@9) */
  w9  = (w5*w9);
  /* #51: @10 = (@10-@9) */
  w10 -= w9;
  /* #52: @24 = (@24+@10) */
  w24 += w10;
  /* #53: @24 = (@24/@12) */
  w24 /= w12;
  /* #54: @8 = (@8/@12) */
  w8 /= w12;
  /* #55: @10 = (2.*@3) */
  w10 = (2.* w3 );
  /* #56: @10 = (@10*@0) */
  w10 *= w0;
  /* #57: @13 = (@13*@10) */
  w13 *= w10;
  /* #58: @8 = (@8*@13) */
  w8 *= w13;
  /* #59: @24 = (@24-@8) */
  w24 -= w8;
  /* #60: @14 = (@14*@23) */
  w14 *= w23;
  /* #61: @2 = (@2*@0) */
  w2 *= w0;
  /* #62: @5 = (@5*@2) */
  w5 *= w2;
  /* #63: @14 = (@14-@5) */
  w14 -= w5;
  /* #64: @7 = (@7*@14) */
  w7 *= w14;
  /* #65: @17 = (@17*@23) */
  w17 *= w23;
  /* #66: @7 = (@7+@17) */
  w7 += w17;
  /* #67: @11 = (@11*@0) */
  w11 *= w0;
  /* #68: @7 = (@7-@11) */
  w7 -= w11;
  /* #69: @7 = (@7/@12) */
  w7 /= w12;
  /* #70: @16 = (@16/@12) */
  w16 /= w12;
  /* #71: @16 = (@16*@13) */
  w16 *= w13;
  /* #72: @7 = (@7-@16) */
  w7 -= w16;
  /* #73: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #74: @21 = vertcat(@18, @22, @24, @7) */
  rr=w21;
  *rr++ = w18;
  *rr++ = w24;
  *rr++ = w7;
  /* #75: @21 = (-@21) */
  for (i=0, rr=w21, cs=w21; i<3; ++i) *rr++ = (- *cs++ );
  /* #76: @25 = @21[:3] */
  for (rr=w25, ss=w21+0; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #77: (@20[:6:2] = @25) */
  for (rr=w20+0, ss=w25; rr!=w20+6; rr+=2) *rr = *ss++;
  /* #78: @18 = ones(4x1,1nz) */
  w18 = 1.;
  /* #79: {NULL, NULL, NULL, @24} = vertsplit(@18) */
  w24 = w18;
  /* #80: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #81: @1 = (@1*@24) */
  w1 *= w24;
  /* #82: @6 = (@6*@1) */
  w6 *= w1;
  /* #83: @6 = (@6/@12) */
  w6 /= w12;
  /* #84: @15 = (@15*@1) */
  w15 *= w1;
  /* #85: @15 = (@15/@12) */
  w15 /= w12;
  /* #86: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #87: @25 = vertcat(@22, @24, @6, @15) */
  rr=w25;
  *rr++ = w24;
  *rr++ = w6;
  *rr++ = w15;
  /* #88: @25 = (-@25) */
  for (i=0, rr=w25, cs=w25; i<3; ++i) *rr++ = (- *cs++ );
  /* #89: @21 = @25[:3] */
  for (rr=w21, ss=w25+0; ss!=w25+3; ss+=1) *rr++ = *ss;
  /* #90: (@20[1:7:2] = @21) */
  for (rr=w20+1, ss=w21; rr!=w20+7; rr+=2) *rr = *ss++;
  /* #91: @26 = @20' */
  casadi_trans(w20,casadi_s1, w26, casadi_s0, iw);
  /* #92: output[1][0] = @26 */
  casadi_copy(w26, 6, res[1]);
  /* #93: @4 = zeros(4x4,4nz) */
  casadi_clear(w4, 4);
  /* #94: @19 = ones(4x1) */
  casadi_fill(w19, 4, 1.);
  /* #95: (@4[:4] = @19) */
  for (rr=w4+0, ss=w19; rr!=w4+4; rr+=1) *rr = *ss++;
  /* #96: @19 = @4' */
  casadi_trans(w4,casadi_s2, w19, casadi_s2, iw);
  /* #97: output[2][0] = @19 */
  casadi_copy(w19, 4, res[2]);
  /* #98: @27 = zeros(1x4,2nz) */
  casadi_clear(w27, 2);
  /* #99: @24 = (1./@12) */
  w24 = (1./ w12 );
  /* #100: @3 = (@3/@12) */
  w3 /= w12;
  /* #101: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #102: @28 = vertcat(@22, @22, @24, @3) */
  rr=w28;
  *rr++ = w24;
  *rr++ = w3;
  /* #103: @28 = (-@28) */
  for (i=0, rr=w28, cs=w28; i<2; ++i) *rr++ = (- *cs++ );
  /* #104: @29 = @28[:2] */
  for (rr=w29, ss=w28+0; ss!=w28+2; ss+=1) *rr++ = *ss;
  /* #105: (@27[:2] = @29) */
  for (rr=w27+0, ss=w29; rr!=w27+2; rr+=1) *rr = *ss++;
  /* #106: output[3][0] = @27 */
  casadi_copy(w27, 2, res[3]);
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_fun_jac_x_xdot_u(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_fun_jac_x_xdot_u_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_fun_jac_x_xdot_u_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_model_impl_dae_fun_jac_x_xdot_u_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_fun_jac_x_xdot_u_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_model_impl_dae_fun_jac_x_xdot_u_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cartpole_model_impl_dae_fun_jac_x_xdot_u_incref(void) {
}

CASADI_SYMBOL_EXPORT void cartpole_model_impl_dae_fun_jac_x_xdot_u_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cartpole_model_impl_dae_fun_jac_x_xdot_u_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int cartpole_model_impl_dae_fun_jac_x_xdot_u_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real cartpole_model_impl_dae_fun_jac_x_xdot_u_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_model_impl_dae_fun_jac_x_xdot_u_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_model_impl_dae_fun_jac_x_xdot_u_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_model_impl_dae_fun_jac_x_xdot_u_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    case 4: return casadi_s5;
    case 5: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_model_impl_dae_fun_jac_x_xdot_u_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s0;
    case 2: return casadi_s2;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_fun_jac_x_xdot_u_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 5;
  if (sz_w) *sz_w = 52;
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_fun_jac_x_xdot_u_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 5*sizeof(casadi_int);
  if (sz_w) *sz_w = 52*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
