/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cartpole_model_impl_dae_fun_jac_x_xdot_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[3] = {0, 3, 5};
static const casadi_int casadi_s1[4] = {1, 2, 4, 6};
static const casadi_int casadi_s2[14] = {4, 4, 0, 0, 3, 3, 7, 0, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s3[14] = {4, 4, 0, 2, 3, 5, 7, 1, 3, 3, 1, 3, 1, 3};
static const casadi_int casadi_s4[11] = {4, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3};
static const casadi_int casadi_s5[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s6[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s7[3] = {0, 0, 0};
static const casadi_int casadi_s8[3] = {4, 0, 0};

/* cartpole_model_impl_dae_fun_jac_x_xdot_z:(i0[4],i1[4],i2,i3[],i4[],i5[])->(o0[4],o1[4x4,7nz],o2[4x4,4nz],o3[4x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, *w4=w+4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, *w18=w+21, *w19=w+25, *w20=w+32, w21, w22, *w24=w+37, *w25=w+40;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #2: @2 = input[1][2] */
  w2 = arg[1] ? arg[1][2] : 0;
  /* #3: @3 = input[1][3] */
  w3 = arg[1] ? arg[1][3] : 0;
  /* #4: @4 = vertcat(@0, @1, @2, @3) */
  rr=w4;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  /* #5: @0 = -0.05 */
  w0 = -5.0000000000000003e-02;
  /* #6: @1 = input[0][1] */
  w1 = arg[0] ? arg[0][1] : 0;
  /* #7: @2 = sin(@1) */
  w2 = sin( w1 );
  /* #8: @3 = (@0*@2) */
  w3  = (w0*w2);
  /* #9: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #10: @6 = sq(@5) */
  w6 = casadi_sq( w5 );
  /* #11: @7 = (@3*@6) */
  w7  = (w3*w6);
  /* #12: @8 = 0.981 */
  w8 = 9.8100000000000009e-01;
  /* #13: @1 = cos(@1) */
  w1 = cos( w1 );
  /* #14: @9 = (@8*@1) */
  w9  = (w8*w1);
  /* #15: @10 = (@9*@2) */
  w10  = (w9*w2);
  /* #16: @7 = (@7+@10) */
  w7 += w10;
  /* #17: @10 = input[2][0] */
  w10 = arg[2] ? arg[2][0] : 0;
  /* #18: @7 = (@7+@10) */
  w7 += w10;
  /* #19: @11 = 1 */
  w11 = 1.;
  /* #20: @12 = 0.1 */
  w12 = 1.0000000000000001e-01;
  /* #21: @13 = sq(@1) */
  w13 = casadi_sq( w1 );
  /* #22: @13 = (@11-@13) */
  w13  = (w11-w13);
  /* #23: @13 = (@12*@13) */
  w13  = (w12*w13);
  /* #24: @11 = (@11+@13) */
  w11 += w13;
  /* #25: @7 = (@7/@11) */
  w7 /= w11;
  /* #26: @13 = (@0*@1) */
  w13  = (w0*w1);
  /* #27: @14 = (@13*@2) */
  w14  = (w13*w2);
  /* #28: @15 = (@14*@6) */
  w15  = (w14*w6);
  /* #29: @16 = 10.791 */
  w16 = 1.0791000000000002e+01;
  /* #30: @17 = (@16*@2) */
  w17  = (w16*w2);
  /* #31: @15 = (@15+@17) */
  w15 += w17;
  /* #32: @17 = (@10*@1) */
  w17  = (w10*w1);
  /* #33: @15 = (@15+@17) */
  w15 += w17;
  /* #34: @15 = (@15/@11) */
  w15 /= w11;
  /* #35: @17 = (2.*@15) */
  w17 = (2.* w15 );
  /* #36: @18 = vertcat(@7, @5, @7, @17) */
  rr=w18;
  *rr++ = w7;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w17;
  /* #37: @4 = (@4-@18) */
  for (i=0, rr=w4, cs=w18; i<4; ++i) (*rr++) -= (*cs++);
  /* #38: output[0][0] = @4 */
  casadi_copy(w4, 4, res[0]);
  /* #39: @19 = zeros(4x4,7nz) */
  casadi_clear(w19, 7);
  /* #40: @20 = ones(4x1,3nz) */
  casadi_fill(w20, 3, 1.);
  /* #41: {NULL, @17, NULL, NULL} = vertsplit(@20) */
  w17 = w20[1];
  /* #42: @21 = (@1*@17) */
  w21  = (w1*w17);
  /* #43: @22 = (@0*@21) */
  w22  = (w0*w21);
  /* #44: @22 = (@6*@22) */
  w22  = (w6*w22);
  /* #45: @9 = (@9*@21) */
  w9 *= w21;
  /* #46: @17 = (@2*@17) */
  w17  = (w2*w17);
  /* #47: @8 = (@8*@17) */
  w8 *= w17;
  /* #48: @8 = (@2*@8) */
  w8  = (w2*w8);
  /* #49: @9 = (@9-@8) */
  w9 -= w8;
  /* #50: @22 = (@22+@9) */
  w22 += w9;
  /* #51: @22 = (@22/@11) */
  w22 /= w11;
  /* #52: @7 = (@7/@11) */
  w7 /= w11;
  /* #53: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #54: @1 = (@1*@17) */
  w1 *= w17;
  /* #55: @12 = (@12*@1) */
  w12 *= w1;
  /* #56: @7 = (@7*@12) */
  w7 *= w12;
  /* #57: @22 = (@22-@7) */
  w22 -= w7;
  /* #58: @23 = 00 */
  /* #59: @13 = (@13*@21) */
  w13 *= w21;
  /* #60: @0 = (@0*@17) */
  w0 *= w17;
  /* #61: @2 = (@2*@0) */
  w2 *= w0;
  /* #62: @13 = (@13-@2) */
  w13 -= w2;
  /* #63: @6 = (@6*@13) */
  w6 *= w13;
  /* #64: @16 = (@16*@21) */
  w16 *= w21;
  /* #65: @6 = (@6+@16) */
  w6 += w16;
  /* #66: @10 = (@10*@17) */
  w10 *= w17;
  /* #67: @6 = (@6-@10) */
  w6 -= w10;
  /* #68: @6 = (@6/@11) */
  w6 /= w11;
  /* #69: @15 = (@15/@11) */
  w15 /= w11;
  /* #70: @15 = (@15*@12) */
  w15 *= w12;
  /* #71: @6 = (@6-@15) */
  w6 -= w15;
  /* #72: @6 = (2.*@6) */
  w6 = (2.* w6 );
  /* #73: @20 = vertcat(@22, @23, @22, @6) */
  rr=w20;
  *rr++ = w22;
  *rr++ = w22;
  *rr++ = w6;
  /* #74: @20 = (-@20) */
  for (i=0, rr=w20, cs=w20; i<3; ++i) *rr++ = (- *cs++ );
  /* #75: @24 = @20[:3] */
  for (rr=w24, ss=w20+0; ss!=w20+3; ss+=1) *rr++ = *ss;
  /* #76: (@19[0, 3, 5] = @24) */
  for (cii=casadi_s0, rr=w19, ss=w24; cii!=casadi_s0+3; ++cii, ++ss) rr[*cii] = *ss;
  /* #77: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #78: @22 = ones(4x1,1nz) */
  w22 = 1.;
  /* #79: {NULL, NULL, NULL, @6} = vertsplit(@22) */
  w6 = w22;
  /* #80: @5 = (@5*@6) */
  w5 *= w6;
  /* #81: @3 = (@3*@5) */
  w3 *= w5;
  /* #82: @3 = (@3/@11) */
  w3 /= w11;
  /* #83: @14 = (@14*@5) */
  w14 *= w5;
  /* #84: @14 = (@14/@11) */
  w14 /= w11;
  /* #85: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #86: @4 = vertcat(@3, @6, @3, @14) */
  rr=w4;
  *rr++ = w3;
  *rr++ = w6;
  *rr++ = w3;
  *rr++ = w14;
  /* #87: @4 = (-@4) */
  for (i=0, rr=w4, cs=w4; i<4; ++i) *rr++ = (- *cs++ );
  /* #88: (@19[1, 2, 4, 6] = @4) */
  for (cii=casadi_s1, rr=w19, ss=w4; cii!=casadi_s1+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #89: @25 = @19' */
  casadi_trans(w19,casadi_s3, w25, casadi_s2, iw);
  /* #90: output[1][0] = @25 */
  casadi_copy(w25, 7, res[1]);
  /* #91: @4 = zeros(4x4,4nz) */
  casadi_clear(w4, 4);
  /* #92: @18 = ones(4x1) */
  casadi_fill(w18, 4, 1.);
  /* #93: (@4[:4] = @18) */
  for (rr=w4+0, ss=w18; rr!=w4+4; rr+=1) *rr = *ss++;
  /* #94: @18 = @4' */
  casadi_trans(w4,casadi_s4, w18, casadi_s4, iw);
  /* #95: output[2][0] = @18 */
  casadi_copy(w18, 4, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_fun_jac_x_xdot_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_fun_jac_x_xdot_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_fun_jac_x_xdot_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_model_impl_dae_fun_jac_x_xdot_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_fun_jac_x_xdot_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_model_impl_dae_fun_jac_x_xdot_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cartpole_model_impl_dae_fun_jac_x_xdot_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void cartpole_model_impl_dae_fun_jac_x_xdot_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cartpole_model_impl_dae_fun_jac_x_xdot_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int cartpole_model_impl_dae_fun_jac_x_xdot_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real cartpole_model_impl_dae_fun_jac_x_xdot_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_model_impl_dae_fun_jac_x_xdot_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_model_impl_dae_fun_jac_x_xdot_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_model_impl_dae_fun_jac_x_xdot_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s7;
    case 5: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_model_impl_dae_fun_jac_x_xdot_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s2;
    case 2: return casadi_s4;
    case 3: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_fun_jac_x_xdot_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 5;
  if (sz_w) *sz_w = 47;
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_model_impl_dae_fun_jac_x_xdot_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 5*sizeof(casadi_int);
  if (sz_w) *sz_w = 47*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
